import { useState } from 'react';

const API_BASE = import.meta.env.VITE_API_URL?.replace('/api', '') || '';
const DEFAULT_WIDTHS = [400, 800, 1600];

/**
 * Responsive image component.
 *
 * Accepts a `src` that may be:
 *  - A DB-stored upload path, e.g. "uploads/covers/xxx.jpg" → emits WebP srcSet
 *    pointing at the variant files generated by the server.
 *  - An absolute URL or static asset path ("/logo.png", "https://...") → plain <img>.
 *
 * Always sets width/height to reserve layout space (avoid CLS).
 *
 * If a WebP variant fails to load (e.g. backfill hasn't run yet), falls back
 * to the original JPEG/PNG.
 */
const Image = ({
  src,
  alt = '',
  width,
  height,
  widths = DEFAULT_WIDTHS,
  sizes,
  priority = false,
  className = '',
  onError,
  ...rest
}) => {
  const [useFallback, setUseFallback] = useState(false);

  if (!src) return null;

  const isUploadOriginal = src.startsWith('uploads/') && /\.(jpe?g|png)$/i.test(src);

  const commonProps = {
    alt,
    width,
    height,
    className,
    loading: priority ? 'eager' : 'lazy',
    fetchPriority: priority ? 'high' : 'auto',
    decoding: 'async',
    ...rest,
  };

  // Not a processable upload path → plain <img> with the URL as-is (prefixed if /uploads).
  if (!isUploadOriginal || useFallback) {
    const finalSrc = src.startsWith('uploads/') ? `${API_BASE}/${src}` : src;
    return <img src={finalSrc} onError={onError} {...commonProps} />;
  }

  const base = src.replace(/\.(jpe?g|png)$/i, '');
  const srcSet = widths.map((w) => `${API_BASE}/${base}-${w}.webp ${w}w`).join(', ');
  const middle = widths[Math.floor(widths.length / 2)];
  const defaultSrc = `${API_BASE}/${base}-${middle}.webp`;

  return (
    <img
      src={defaultSrc}
      srcSet={srcSet}
      sizes={sizes}
      onError={(e) => {
        setUseFallback(true);
        if (onError) onError(e);
      }}
      {...commonProps}
    />
  );
};

export default Image;
